export {
  describeFile,
  detectFormat,
  renderText,
  UnsupportedFormatError,
} from './representations/index.js'
export type {
  DescribeFileResult,
  FormatId,
  RepresentationDocument,
  RepresentationSection,
} from './representations/index.js'
export {
  AgentStreamParser,
  ENGINEERING_AGENT_SYSTEM_PROMPT,
  OPENROUTER_API_BASE,
  OpenRouterError,
  agentReply,
  buildEngineeringSystemPrompt,
  buildModelingWorkflowBrief,
  buildWorkspaceContext,
  chatCompletion,
  createSession,
  createToolCard,
  describeWorkspaceFile,
  engineeringToolDefinitions,
  extractStreamChunk,
  lastUserMessage,
  listModels,
  providerLabel,
  reduce,
  streamAgentReply,
  streamChatCompletion,
  streamChatCompletionChunks,
  toOpenRouterMessages,
  toolTitles,
  workspaceContextMessage,
} from './agent/index.js'
export type {
  AgentMessageOptions,
  AgentReplyOptions,
  AgentToolCard,
  ChatCompletionOptions,
  ChatCompletionStreamChunk,
  ChatMessage,
  ChatRole,
  ChatSession,
  ListModelsQuery,
  OpenRouterChatMessage,
  OpenRouterChatRole,
  OpenRouterClientOptions,
  OpenRouterContentPart,
  OpenRouterFileContentPart,
  OpenRouterFunctionTool,
  OpenRouterImageContentPart,
  OpenRouterModality,
  OpenRouterModel,
  OpenRouterServerTool,
  OpenRouterTextContentPart,
  OpenRouterTool,
  SessionEvent,
  StreamParserEvent,
  ToolKind,
  WindowMode,
  WorkspaceContext,
  WorkspaceContextOptions,
  WorkspaceFileContext,
  WorkspaceFileSnapshot,
} from './agent/index.js'
